# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55cff46b87909fddd4280d1a41253bbd"
name = "Fitted"
application_url = "https://fitted-api.fly.dev"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shopify"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://fitted-api.fly.dev/api/shopify/callback",
  "https://fitted-api.fly.dev/auth/callback"
]

[pos]
embedded = true
